//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Host.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ServiceReference1.SecurityTokenService")]
    public interface SecurityTokenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue", ReplyAction="http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/Issue")]
        System.ServiceModel.Channels.Message ProcessRequestSecurityToken(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue", ReplyAction="http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/Issue")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ProcessRequestSecurityTokenAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecurityTokenServiceChannel : Host.ServiceReference1.SecurityTokenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityTokenServiceClient : System.ServiceModel.ClientBase<Host.ServiceReference1.SecurityTokenService>, Host.ServiceReference1.SecurityTokenService {
        
        public SecurityTokenServiceClient() {
        }
        
        public SecurityTokenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityTokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityTokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityTokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message ProcessRequestSecurityToken(System.ServiceModel.Channels.Message request) {
            return base.Channel.ProcessRequestSecurityToken(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ProcessRequestSecurityTokenAsync(System.ServiceModel.Channels.Message request) {
            return base.Channel.ProcessRequestSecurityTokenAsync(request);
        }
    }
}
